root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  include_ext = ["go", "html", "png", "svg"]
  exclude_dir = ["tmp", "vendor"]
  delay = 200
  kill_delay = "0s"
  rerun_delay = 500

[log]
  time = false
  main_only = true

[misc]
  clean_on_exit = true
